{"level":"ERROR","location":"[access_token_to_hsmtoken:287] data_ws","message":{"type":"cn","code":-300,"message":"Please provide valid token","s":"error"},"timestamp":"2024-07-13 17:32:40,407+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[On_error:261] order_ws","message":"Handshake status 403 Forbidden -+-+- {'date': 'Sat, 13 Jul 2024 12:04:50 GMT', 'content-length': '0', 'connection': 'keep-alive', 'cf-cache-status': 'DYNAMIC', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'server': 'cloudflare', 'cf-ray': '8a2923474ea4f2de-BOM'} -+-+- b''","timestamp":"2024-07-13 17:34:50,628+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_error:261] order_ws","message":"Handshake status 403 Forbidden -+-+- {'date': 'Sat, 13 Jul 2024 12:04:55 GMT', 'content-length': '0', 'connection': 'keep-alive', 'cf-cache-status': 'DYNAMIC', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'server': 'cloudflare', 'cf-ray': '8a2923694d74f296-BOM'} -+-+- b''","timestamp":"2024-07-13 17:34:56,003+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_error:261] order_ws","message":"Handshake status 403 Forbidden -+-+- {'date': 'Sat, 13 Jul 2024 12:05:02 GMT', 'content-length': '0', 'connection': 'keep-alive', 'cf-cache-status': 'DYNAMIC', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'server': 'cloudflare', 'cf-ray': '8a29238e3a2b9aa5-NAG'} -+-+- b''","timestamp":"2024-07-13 17:35:02,119+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_error:261] order_ws","message":"Handshake status 403 Forbidden -+-+- {'date': 'Sat, 13 Jul 2024 12:05:07 GMT', 'content-length': '0', 'connection': 'keep-alive', 'cf-cache-status': 'DYNAMIC', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'server': 'cloudflare', 'cf-ray': '8a2923b06b1f79ee-HYD'} -+-+- b''","timestamp":"2024-07-13 17:35:07,526+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_error:261] order_ws","message":"Handshake status 403 Forbidden -+-+- {'date': 'Sat, 13 Jul 2024 12:05:12 GMT', 'content-length': '0', 'connection': 'keep-alive', 'cf-cache-status': 'DYNAMIC', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'server': 'cloudflare', 'cf-ray': '8a2923d41eb1f2da-BOM'} -+-+- b''","timestamp":"2024-07-13 17:35:13,174+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_error:261] order_ws","message":"Handshake status 403 Forbidden -+-+- {'date': 'Sat, 13 Jul 2024 12:05:18 GMT', 'content-length': '0', 'connection': 'keep-alive', 'cf-cache-status': 'DYNAMIC', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'server': 'cloudflare', 'cf-ray': '8a2923f889b2f347-BOM'} -+-+- b''","timestamp":"2024-07-13 17:35:18,953+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"EOF occurred in violation of protocol (_ssl.c:2406)","timestamp":"2024-07-13 21:01:05,675+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2024-07-13 21:01:10,685+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"'FyersModel' object has no attribute 'subscribe'","timestamp":"2024-07-13 23:02:58,837+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_app.py\", line 428, in setSock\n    dispatcher.read(self.sock.sock, read, check)\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_app.py\", line 99, in read\n    if not read_callback():\n           ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_app.py\", line 437, in read\n    op_code, frame = self.sock.recv_data_frame(True)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_core.py\", line 427, in recv_data_frame\n    self.pong(frame.data)\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_core.py\", line 351, in pong\n    self.send(payload, ABNF.OPCODE_PONG)\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_core.py\", line 283, in send\n    return self.send_frame(frame)\n           ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_core.py\", line 311, in send_frame\n    l = self._send(data)\n        ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_core.py\", line 525, in _send\n    return send(self.sock, data)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_socket.py\", line 170, in send\n    return _send()\n           ^^^^^^^\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_socket.py\", line 147, in _send\n    return sock.send(data)\n           ^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python312\\Lib\\ssl.py\", line 1180, in send\n    return self._sslobj.write(data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\nssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2406)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"C:\\Users\\IN00395\\AppData\\Local\\Temp\\ipykernel_21492\\3047453832.py\", line 48, in onopen\n    fyers.subscribe(symbols=symbols, data_type=data_type)\n    ^^^^^^^^^^^^^^^\nAttributeError: 'FyersModel' object has no attribute 'subscribe'","exception_name":"AttributeError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"'FyersModel' object has no attribute 'subscribe'","timestamp":"2024-07-13 23:02:58,853+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2024-07-13 23:02:58,856+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"'FyersModel' object has no attribute 'subscribe'","timestamp":"2024-07-13 23:03:00,837+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_http.py\", line 155, in _get_addrinfo_list\n    addrinfo_list = socket.getaddrinfo(\n                    ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python312\\Lib\\socket.py\", line 964, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno 11001] getaddrinfo failed\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_app.py\", line 412, in setSock\n    self.sock.connect(\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_core.py\", line 249, in connect\n    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_http.py\", line 122, in connect\n    addrinfo_list, need_tunnel, auth = _get_addrinfo_list(\n                                       ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_http.py\", line 167, in _get_addrinfo_list\n    raise WebSocketAddressException(e)\nwebsocket._exceptions.WebSocketAddressException: [Errno 11001] getaddrinfo failed\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"C:\\Users\\IN00395\\AppData\\Local\\Temp\\ipykernel_21492\\3047453832.py\", line 48, in onopen\n    fyers.subscribe(symbols=symbols, data_type=data_type)\n    ^^^^^^^^^^^^^^^\nAttributeError: 'FyersModel' object has no attribute 'subscribe'","exception_name":"AttributeError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"'FyersModel' object has no attribute 'subscribe'","timestamp":"2024-07-13 23:03:00,842+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2024-07-13 23:03:03,861+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"'FyersModel' object has no attribute 'subscribe'","timestamp":"2024-07-13 23:03:05,859+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_http.py\", line 155, in _get_addrinfo_list\n    addrinfo_list = socket.getaddrinfo(\n                    ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python312\\Lib\\socket.py\", line 964, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno 11001] getaddrinfo failed\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_app.py\", line 412, in setSock\n    self.sock.connect(\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_core.py\", line 249, in connect\n    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_http.py\", line 122, in connect\n    addrinfo_list, need_tunnel, auth = _get_addrinfo_list(\n                                       ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_http.py\", line 167, in _get_addrinfo_list\n    raise WebSocketAddressException(e)\nwebsocket._exceptions.WebSocketAddressException: [Errno 11001] getaddrinfo failed\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"C:\\Users\\IN00395\\AppData\\Local\\Temp\\ipykernel_21492\\3047453832.py\", line 48, in onopen\n    fyers.subscribe(symbols=symbols, data_type=data_type)\n    ^^^^^^^^^^^^^^^\nAttributeError: 'FyersModel' object has no attribute 'subscribe'","exception_name":"AttributeError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"'FyersModel' object has no attribute 'subscribe'","timestamp":"2024-07-13 23:03:05,863+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2024-07-15 10:59:56,594+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"'FyersModel' object has no attribute 'subscribe'","timestamp":"2024-07-15 10:59:58,598+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_http.py\", line 155, in _get_addrinfo_list\n    addrinfo_list = socket.getaddrinfo(\n                    ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python312\\Lib\\socket.py\", line 964, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno 11001] getaddrinfo failed\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_app.py\", line 412, in setSock\n    self.sock.connect(\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_core.py\", line 249, in connect\n    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_http.py\", line 122, in connect\n    addrinfo_list, need_tunnel, auth = _get_addrinfo_list(\n                                       ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\websocket\\_http.py\", line 167, in _get_addrinfo_list\n    raise WebSocketAddressException(e)\nwebsocket._exceptions.WebSocketAddressException: [Errno 11001] getaddrinfo failed\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\IN00395\\AppData\\Roaming\\Python\\Python312\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"C:\\Users\\IN00395\\AppData\\Local\\Temp\\ipykernel_21492\\3047453832.py\", line 48, in onopen\n    fyers.subscribe(symbols=symbols, data_type=data_type)\n    ^^^^^^^^^^^^^^^\nAttributeError: 'FyersModel' object has no attribute 'subscribe'","exception_name":"AttributeError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"'FyersModel' object has no attribute 'subscribe'","timestamp":"2024-07-15 10:59:58,608+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_error:261] order_ws","message":"Handshake status 403 Forbidden -+-+- {'date': 'Tue, 16 Jul 2024 10:05:48 GMT', 'content-length': '0', 'connection': 'keep-alive', 'cf-cache-status': 'DYNAMIC', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'server': 'cloudflare', 'cf-ray': '8a412d0c6e0c3a19-BOM'} -+-+- b''","timestamp":"2024-07-16 15:35:48,936+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_error:261] order_ws","message":"Handshake status 403 Forbidden -+-+- {'date': 'Tue, 16 Jul 2024 10:05:54 GMT', 'content-length': '0', 'connection': 'keep-alive', 'cf-cache-status': 'DYNAMIC', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'server': 'cloudflare', 'cf-ray': '8a412d2e4919857b-BOM'} -+-+- b''","timestamp":"2024-07-16 15:35:54,857+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_error:261] order_ws","message":"Handshake status 403 Forbidden -+-+- {'date': 'Tue, 16 Jul 2024 10:05:59 GMT', 'content-length': '0', 'connection': 'keep-alive', 'cf-cache-status': 'DYNAMIC', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'server': 'cloudflare', 'cf-ray': '8a412d519d7c3e22-BOM'} -+-+- b''","timestamp":"2024-07-16 15:35:59,972+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_error:261] order_ws","message":"Handshake status 403 Forbidden -+-+- {'date': 'Tue, 16 Jul 2024 10:06:05 GMT', 'content-length': '0', 'connection': 'keep-alive', 'cf-cache-status': 'DYNAMIC', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'server': 'cloudflare', 'cf-ray': '8a412d71bc004206-BOM'} -+-+- b''","timestamp":"2024-07-16 15:36:05,119+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_error:261] order_ws","message":"Handshake status 403 Forbidden -+-+- {'date': 'Tue, 16 Jul 2024 10:06:11 GMT', 'content-length': '0', 'connection': 'keep-alive', 'cf-cache-status': 'DYNAMIC', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'server': 'cloudflare', 'cf-ray': '8a412d983a5a4719-BOM'} -+-+- b''","timestamp":"2024-07-16 15:36:11,348+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_error:261] order_ws","message":"Handshake status 403 Forbidden -+-+- {'date': 'Tue, 16 Jul 2024 10:06:16 GMT', 'content-length': '0', 'connection': 'keep-alive', 'cf-cache-status': 'DYNAMIC', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'server': 'cloudflare', 'cf-ray': '8a412dba7f5d4461-BOM'} -+-+- b''","timestamp":"2024-07-16 15:36:16,837+0530","service":"FyersDataSocket"}
